<script setup>
import { ref, computed, onMounted, nextTick, watch } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { useMeetingsStore } from '../stores/meetingsStore'
import { useTasksStore } from '../stores/tasksStore'
import { useUsersStore } from '../stores/usersStore'
import { useListsStore } from '../stores/listsStore'
import { usePreferencesStore } from '../stores/preferencesStore'
import { useFiltersStore } from '../stores/filtersStore'
import { useIsAdmin } from '../composables/usePermissions'
import { useAssignableUsers } from '../composables/useAssignableUsers'
import TaskListPanel from '../components/task/TaskListPanel.vue'
import QuickAddTaskRow from '../components/task/QuickAddTaskRow.vue'
import QuickFiltersBar from '../components/common/QuickFiltersBar.vue'
import AppIcon from '../components/common/AppIcon.vue'
import RichTextEditor from '../components/common/RichTextEditor.vue'
import ConfirmModal from '../components/common/ConfirmModal.vue'
import UserMultiSelect from '../components/common/UserMultiSelect.vue'
import OccurrenceTaskGlance from '../components/task/OccurrenceTaskGlance.vue'
import { formatDateTime, formatTime, formatMeetingRecurrence } from '../utils/formatters'
import { meetingSummaryParser, MATCHED_PATTERN_LABEL } from '../services/MeetingSummaryParser'
import { meetingOccurrenceService } from '../services/MeetingOccurrenceService'

const props = defineProps({ id: { type: String, required: true } }); const router = useRouter(); const route = useRoute(); const meetingsStore = useMeetingsStore(); const tasksStore = useTasksStore(); const usersStore = useUsersStore(); const listsStore = useListsStore(); const prefs = usePreferencesStore(); const filtersStore = useFiltersStore(); const isAdmin = useIsAdmin(); const assignableUsers = useAssignableUsers(() => ({ meetingId: props.id }))
const editing = ref(false); const editDraft = ref({ title: '', date: '', time: '', description: '', link: '', attendeeIds: [], editorIds: [], color: '#4f7cff', recurrenceEnabled: false, recurrenceFreq: 'weekly', recurrenceWeekdays: [] }); const showSummaryParser = ref(false); const summaryText = ref(''); const parsedCandidates = ref([]); const parseAttempted = ref(false); const selectedSummaryOccurrenceId = ref('all'); const activeOccurrence = ref(null); const occurrenceDraft = ref({ description: '', link: '' }); const occurrenceEditing = ref(false); const expandedOccurrenceIds = ref([]); const addingOccurrence = ref(false); const newOccurrenceDraft = ref({ date: '', time: '', description: '', link: '' }); const newOccurrenceParsedCandidates = ref([]); const newOccurrenceParseAttempted = ref(false); const occurrencePendingRemoval = ref(null); const meetingPendingRemoval = ref(false)
const WEEKDAY_OPTIONS = [{ value: 1, label: 'Пн' }, { value: 2, label: 'Вт' }, { value: 3, label: 'Ср' }, { value: 4, label: 'Чт' }, { value: 5, label: 'Пт' }, { value: 6, label: 'Сб' }, { value: 0, label: 'Вс' }]
function scrollToOccurrenceHash() { const hash = route.hash || ''; if (!hash.startsWith('#occurrence-')) return; nextTick(() => document.querySelector(hash)?.scrollIntoView({ behavior: 'smooth', block: 'start' })) }
onMounted(async () => { if (!meetingsStore.loaded) await meetingsStore.load(); if (!tasksStore.loaded) await tasksStore.load(); if (!listsStore.loaded) await listsStore.load(); if (!usersStore.loaded) await usersStore.load(); if (isRecurring.value) filtersStore.setStatus('all'); scrollToOccurrenceHash() }); watch(() => route.hash, scrollToOccurrenceHash)
const meeting = computed(() => meetingsStore.meetingById(props.id)); const author = computed(() => meeting.value ? usersStore.byId(meeting.value.createdBy) : null); const isRecurring = computed(() => !!meeting.value?.recurrence?.freq); const meetingTasks = computed(() => tasksStore.tasks.filter((t) => t.meetingId === props.id && !t.parentTaskId)); const attendees = computed(() => (meeting.value?.attendeeIds || []).map((id) => usersStore.byId(id)).filter(Boolean)); const meetingFilterUsers = computed(() => { const ids = new Set([...(meeting.value?.attendeeIds || []), ...meetingTasks.value.map((t) => t.assigneeId).filter(Boolean)]); return usersStore.users.filter((u) => ids.has(u.id)) }); const recurrenceLabel = computed(() => formatMeetingRecurrence(meeting.value?.recurrence)); const occurrences = computed(() => meetingsStore.occurrencesOf(props.id)); const activeOccurrenceTasks = computed(() => activeOccurrence.value ? meetingTasks.value.filter((t) => t.occurrenceId === activeOccurrence.value.id) : [])
function occurrenceTitle(occ) { return `${meeting.value?.title || ''} · ${formatDateTime(occ.date)}` }; function isOccurrenceExpanded(id) { return expandedOccurrenceIds.value.includes(id) }; function toggleOccurrenceDescription(id) { expandedOccurrenceIds.value = isOccurrenceExpanded(id) ? expandedOccurrenceIds.value.filter((x) => x !== id) : [...expandedOccurrenceIds.value, id] }; const filteredMeetingTasks = computed(() => filtersStore.apply(meetingTasks.value)); const recurringVisibleTasks = computed(() => { if (!isRecurring.value) return []; let list = filteredMeetingTasks.value; if (!prefs.showCompleted && prefs.groupBy !== 'bubble') list = list.filter((t) => t.status !== 'done' && t.status !== 'cancelled'); return list }); const occurrenceGroups = computed(() => isRecurring.value ? occurrences.value.map((occ, i) => ({ occurrence: occ, tasks: recurringVisibleTasks.value.filter((t) => t.occurrenceId === occ.id), order: i })).sort((a, b) => a.order - b.order) : [])
const relatedListIds = computed(() => new Set(meetingTasks.value.map((t) => t.listId).filter(Boolean)); const standaloneUnfinishedTasks = computed(() => isRecurring.value && relatedListIds.value.size ? tasksStore.tasks.filter((t) => !t.parentTaskId && !t.meetingId && relatedListIds.value.has(t.listId) && !['done', 'cancelled'].includes(t.status)).sort((a, b) => new Date(a.updatedAt || a.createdAt || 0) - new Date(b.updatedAt || b.createdAt || 0)) : []); const unfinishedSeriesTasksWithoutOccurrence = computed(() => isRecurring.value ? meetingTasks.value.filter((t) => !t.occurrenceId && !['done', 'cancelled'].includes(t.status)).sort((a, b) => new Date(a.updatedAt || a.createdAt || 0) - new Date(b.updatedAt || b.createdAt || 0)) : []); const unfinishedGroupsByOccurrence = computed(() => isRecurring.value ? occurrences.value.map((occ, i) => { const tasks = meetingTasks.value.filter((t) => t.occurrenceId === occ.id && !['done', 'cancelled'].includes(t.status)); return { occurrence: occ, tasks, count: tasks.length, order: i } }).filter((g) => g.count) : []); const unfinishedTotalCount = computed(() => unfinishedGroupsByOccurrence.value.reduce((sum, g) => sum + g.count, 0) + standaloneUnfinishedTasks.value.length + unfinishedSeriesTasksWithoutOccurrence.value.length); const shouldShowTopAddOccurrenceButton = computed(() => canManageMeeting.value && unfinishedTotalCount.value > 4)
const canManageMeeting = computed(() => { if (!meeting.value) return false; if (isAdmin.value || meeting.value.createdBy === usersStore.currentUser?.id) return true; return [...new Set(meetingTasks.value.map((t) => t.listId).filter(Boolean))].some((id) => ['owner', 'editor'].includes(listsStore.memberships[id]?.find((m) => m.userId === usersStore.currentUser?.id)?.role)) })
const summaryOccurrenceOptions = computed(() => occurrences.value.map((o) => ({ id: o.id, label: occurrenceTitle(o) })))
</script>

<template>
  <div v-if="!meeting" class="empty-state">Встреча не найдена или была удалена.</div>
  <template v-else>
    <div class="view-header"><div class="view-title"><button class="btn btn-ghost btn-sm back-btn" @click="router.push('/meetings')"><AppIcon name="chevronLeft" :size="13" /> Встречи</button></div></div>
    <div class="meeting-header card"><h2 class="meeting-title"><span class="meeting-color-dot" :style="{ background: meeting.color || '#4f7cff' }" /><AppIcon :name="isRecurring ? 'repeat' : 'calendar'" :size="17" /> {{ meeting.title }}</h2><div class="meeting-meta meeting-meta-wrap"><span class="meta-item"><AppIcon name="alarm" :size="12" /> {{ isRecurring ? formatTime(meeting.date) : formatDateTime(meeting.date) }}</span><span class="meeting-recurrence meta-item"><AppIcon :name="isRecurring ? 'repeat' : 'calendar'" :size="12" /> {{ recurrenceLabel }}</span><a v-if="meeting.link" :href="meeting.link" target="_blank" rel="noopener" class="meta-item meeting-link"><AppIcon name="link" :size="12" /> Присоединиться к звонку</a><span v-if="author">· Автор: {{ author.name }}</span></div><div v-if="meeting.description" class="meeting-description rte-render" v-html="meeting.description" /></div>
    <template v-if="isRecurring"><div class="occurrences-header-row"><h3 class="tasks-title occurrences-title">Подвстречи серии</h3></div><QuickFiltersBar :task-count="recurringVisibleTasks.length" :meeting-mode="false" :assignee-users="meetingFilterUsers" /><div class="occurrence-list"><div v-for="group in occurrenceGroups" :id="`occurrence-${group.occurrence.id}`" :key="group.occurrence.id" class="occurrence-card card"><button class="occurrence-header" @click="openOccurrence(group.occurrence)"><span class="occurrence-date"><AppIcon name="calendar" :size="13" /> {{ occurrenceTitle(group.occurrence) }}</span></button><TaskListPanel v-if="group.tasks.length" :tasks="group.tasks" :show-toolbar="false" :meeting-mode="true" /><div v-else class="empty-state-inline">Задач на встрече нет</div></div></div></template><template v-else><h3 class="tasks-title">Задачи встречи</h3><QuickFiltersBar :task-count="meetingTasks.length" :meeting-mode="true" :assignee-users="meetingFilterUsers" /><TaskListPanel :tasks="meetingTasks" :meeting-mode="true" empty-text="К этой встрече пока не привязано ни одной задачи" /></template>
  </template>
</template>

<style scoped>.view-header { display:flex; align-items:center; justify-content:space-between; margin-bottom:10px; }.meeting-header { padding:16px 18px; margin-bottom:18px; }.meeting-title { margin:0 0 6px; font-size:18px; display:flex; align-items:center; gap:8px; }.meeting-color-dot { width:10px; height:10px; border-radius:50%; }.meeting-meta { display:flex; gap:10px; font-size:12.5px; color:var(--color-text-muted); margin-bottom:8px; }.meeting-meta-wrap { flex-wrap:wrap; }.meta-item { display:inline-flex; align-items:center; gap:5px; }.meeting-recurrence { color:var(--color-text); font-weight:500; }.meeting-link { color:var(--color-primary); font-weight:600; text-decoration:none; }.meeting-description { font-size:13px; color:var(--color-text); line-height:1.5; }.tasks-title { font-size:13px; font-weight:600; margin:0 0 8px; color:var(--color-text-muted); text-transform:uppercase; }.occurrences-header-row { display:flex; align-items:center; justify-content:space-between; margin-top:20px; }.occurrence-list { display:flex; flex-direction:column; gap:12px; }.occurrence-card { padding:12px 14px; scroll-margin-top:18px; }.occurrence-header { display:flex; align-items:center; gap:10px; width:100%; border:none; background:none; cursor:pointer; padding:4px 2px 8px; text-align:left; }.occurrence-date { font-size:13.5px; font-weight:600; display:inline-flex; align-items:center; gap:6px; }.empty-state-inline { font-size:12.5px; color:var(--color-text-muted); padding:10px; text-align:center; }</style>
